ALTER TABLE users ADD COLUMN current_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN longest_streak INTEGER NOT NULL DEFAULT 0;
ALTER TABLE users ADD COLUMN last_active_date DATE;
ALTER TABLE users ADD COLUMN unlocked_themes TEXT[] NOT NULL DEFAULT ARRAY['default']::TEXT[];
